-- 门店线下零售宽表建表 DDL（存档，来源：一体化项目相关.sql）
-- 下次查门店线下订单字段口径时看这里；实际取数用 scripts/sql/07_mendian_offline_orders.sql

-- ========================================================================
-- 表1：小店线下零售宽表
-- hdp_zhuanzhuan_dw_global.dw_trade_retail_offline_data_full_1d
-- COMMENT '帮卖业务，线下门店零售业务宽表'
-- 分区 dt(string)；关键字段：order_id(销售父订单id/线下为oms出库单号) / city_name / outbound_time /
--   order_type(1门店订单 2线下销售 3同售订单 4严选订单) / order_state / store_name /
--   store_type(0自营 2测试 5加盟) / is_hour_mart(是否上架小时达) / is_mart(是否同售) / deal_price(分)
-- ========================================================================
CREATE EXTERNAL TABLE `hdp_zhuanzhuan_dw_global.dw_trade_retail_offline_data_full_1d`(
  `purchase_id` bigint COMMENT '进货单id',
  `product_pool_id` bigint COMMENT '进货商品明细id',
  `create_time` string COMMENT '商品进货单创建时间，形式yyyy-MM-dd HH:mm:ss',
  `audit_time` string COMMENT '审批时间，形式yyyy-MM-dd HH:mm:ss',
  `purchase_type` tinyint COMMENT '字段废弃，拆分为purchase_order_source和purchaser_type',
  `city_name` string COMMENT '城市，严选订单为销售城市',
  `store_name` string COMMENT '进货门店，如发生调拨，此处为调拨门店，严选订单为销售门店',
  `approver` string COMMENT '审批人',
  `proposer` string COMMENT '创建人',
  `purchase_order_state` tinyint COMMENT '进货订单状态，1待处理，2处理中，3已完成，4已取消',
  `audit_state` tinyint COMMENT '进货订单审批状态，1待审批，2审批通过，3审批驳回',
  `purchase_deal_time` string COMMENT '进货商品处理时间，形式yyyy-MM-dd HH:mm:ss',
  `purchase_info_state` tinyint COMMENT '进货商品状态，1待处理，2已驳回，3已分配，4无库存',
  `sku_id` bigint COMMENT 'sku_id',
  `qc_code` bigint COMMENT '质检码',
  `cate_name` string COMMENT '品类名',
  `brand_name` string COMMENT '品牌名',
  `model_name` string COMMENT '机型名',
  `capacity_desc` string COMMENT '容量描述',
  `valuer_grade_desc` string COMMENT '等级描述',
  `condition_desc` string COMMENT '成色描述',
  `purchase_price` bigint COMMENT '进货价（分）',
  `init_retail_price` bigint COMMENT '初始零售价（分）',
  `reference_retail_price` bigint COMMENT '零售参考价（分）',
  `purchase_channels` tinyint COMMENT '1天路，2保卖竞拍, 3.售后退回 4.入仓质检 5权益机 6-权益机售后退回',
  `storage_age` int COMMENT '库龄',
  `inspect_result` tinyint COMMENT '检验结论，1正常，2瑕疵，4异常',
  `inspect_name` string COMMENT '检验人',
  `logistics_num` string COMMENT '物流单号',
  `storage_state` tinyint COMMENT '库存商品状态，1待入库，2已入库，3待出库，4已出库',
  `storage_time` string COMMENT '商品首次入库时间，形式yyyy-MM-dd HH:mm:ss',
  `outbound_time` string COMMENT '商品出库时间，形式yyyy-MM-dd HH:mm:ss',
  `is_update_price` tinyint COMMENT '是否调整零售价，1是，0否',
  `info_id` bigint COMMENT '销售商品id',
  `order_id` bigint COMMENT '销售父订单id,，线下销售为oms出库单号',
  `staff_name` string COMMENT '销售人',
  `buyer_id` bigint COMMENT '买家uid',
  `deal_price` bigint COMMENT '成交价（分）',
  `pay_type` tinyint COMMENT '支付方式，1微信支付，2支付宝支付，0其他',
  `order_state` int COMMENT '10已下单，20已完成，30已关闭，40同售完成,50售后订单,11严选已下单 ,60严选已完成  70权益机已完成',
  `is_refund` tinyint COMMENT '是否退款，1是，0否',
  `recall_state` tinyint COMMENT '召回状态，1待处理，2处理中，3待确认，4已完成，5待审批，6质检中，7销售中，-1已关闭',
  `recall_reason` tinyint COMMENT '召回原因，1超库龄召回，2检验异常召回',
  `recall_type` tinyint COMMENT '召回方式，1总部，2采货侠',
  `confirm_recall_time` string COMMENT '确认召回时间，形式yyyy-MM-dd HH:mm:ss',
  `recall_logistics_num` string COMMENT '召回物流单号',
  `store_id` bigint COMMENT '进货门店id，如发生调拨，此处为调拨门店',
  `gold_level_name` string COMMENT '新质检等级',
  `retail_price` bigint COMMENT '零售价调价（分）',
  `reserve_type` string COMMENT '预定方式',
  `reserve_time` string COMMENT '预定取货时间，形式yyyy-MM-dd',
  `child_order_id` bigint COMMENT '销售子订单id，严选订单为oms出库单号',
  `pack_amt` bigint COMMENT '红包金额（分）',
  `point_amt` bigint COMMENT '积分金额（分）',
  `product_source` int COMMENT '1保卖CZB,2端外渠道3,YYJ_RETURN_GOODS,4保卖CZC,5手动录入,6上门回收,7 门店回收,8售后平台吃货',
  `product_source_desc` string COMMENT '进货商品来源描述',
  `is_allot` int COMMENT '1是，0不是',
  `to_warehouse_id` bigint COMMENT '被调拨门店id',
  `to_warehouse_name` string COMMENT '被调拨门店名称',
  `order_type` int COMMENT '订单类型，1.门店订单，2.线下销售，3.同售订单，4.严选订单',
  `order_type_desc` string COMMENT '订单类型，1.门店订单，2.线下销售，3.同售订单，4.严选订单',
  `pay_time` string COMMENT 'yyyy-MM-dd HH:mm:ss',
  `relate_id` bigint COMMENT '服务id',
  `relate_desc` string COMMENT '服务名称',
  `allot_outbound_time` string COMMENT 'yyyy-MM-dd HH:mm:ss',
  `allot_city_name` string COMMENT '被调拨城市名称',
  `is_mart` int COMMENT '是否同售,1.是，2.否',
  `mart_type` int COMMENT '同售卖场,1严选  ',
  `mart_state` int COMMENT '同售状态,1待上架，2上架中，3销售中，4已售出，5下架中，6已下架',
  `strict_initial_price` bigint COMMENT '严选初始价格（分）',
  `is_strict_price` int COMMENT '是否调整严选价格,1-是调整，0-没有调整',
  `strict_price` bigint COMMENT '严选调价（分）',
  `actual_cost_price` bigint COMMENT '实际成本价（分）',
  `strict_retail_price` bigint COMMENT '严选零售价（如未发生调整严选价格则取严选初始价格，如发生调整严选价格则展示调整后的价格）',
  `capacity_id` bigint COMMENT '容量id',
  `ram_id` bigint COMMENT '运行内存id',
  `ram` string COMMENT '运行内存',
  `memory_capacity_id` bigint COMMENT '存储容量id',
  `memory_capacity` string COMMENT '存储容量',
  `product_type` int COMMENT '销售类型 商品类型：1销售 2调拨 3售后',
  `mart_time` string COMMENT '上架时间 yyyy-MM-dd HH:mm:ss',
  `imei` string COMMENT 'IMEI',
  `cate_id` bigint COMMENT '品类ID',
  `brand_id` bigint COMMENT '品牌ID',
  `model_id` bigint COMMENT '型号ID',
  `condition_id` bigint COMMENT '成色ID',
  `official_price` bigint COMMENT '新机价（分）',
  `price_reasons` string COMMENT '调价原因',
  `is_reserve` int COMMENT '是否预定 (1.是 ,0.否)',
  `is_reserve_time` int COMMENT '是否按预定时间取货 (1.是,0.否)',
  `is_need_recall` int COMMENT '是否标记召回(1.是,0.否)',
  `is_afs` int COMMENT '是否有售后 1.有，0.没有',
  `warranty_id` bigint COMMENT '保修情况id',
  `warranty` string COMMENT '保修情况',
  `is_price_reduce` int COMMENT '超库龄降价  1.是，0.否',
  `is_pre_price_adjust` int COMMENT '周期调价   1.是，0.否',
  `is_def_price_reduce` int COMMENT '瑕疵降价   1.是，0.否',
  `check_problem` string COMMENT '检验问题',
  `is_sell_high_price` int COMMENT '门店高价售卖   1.是，0.否',
  `create_by` string COMMENT '调价人',
  `price_adjustment_amt` bigint COMMENT '调价金额（分）',
  `market_channel` int COMMENT '销售渠道：0. 无， 1. 线下用户， 2. 微信/社群沟通，3 .大众点评/地图，4.抖音/其他网络平台，5.朋友介绍，6.老用户复购',
  `b2b_order_id` bigint COMMENT '采货侠订单ID',
  `b2b_price` bigint COMMENT '散货金额(分)',
  `recall_create_time` string COMMENT '召回创建时间 yyyy-MM-dd HH:mm:ss',
  `recall_outbound_time` string COMMENT '召回出库时间 yyyy-MM-dd HH:mm:ss',
  `up_price` bigint COMMENT '店员加价金额(分)',
  `initial_purchase_price` bigint COMMENT '初始进货价(分)',
  `sale_channel` string COMMENT '售出渠道：门店售出，非门店售出，商户召回',
  `purchase_price_change` int COMMENT '进货价是否变更(1 是 0否)',
  `initial_purchase_channels` bigint COMMENT '初始进货渠道，1.天路 4.入仓质检',
  `no_sale_reason` string COMMENT '无法销售原因(销售库存不足/成本上调/零售价调整毛利额不符/毛利额过低无法上架)',
  `not_store_sale_node` string COMMENT '非门店售出节点(出库前售出/物流在途售出/在门店售出)',
  `reserve_op_time` string COMMENT '最新标记预定操作时间',
  `store_type` tinyint COMMENT '门店类型 0自营2测试门店5加盟',
  `city_id` int COMMENT '如发生调拨，此处为调拨门店城市id，严选订单为销售门店城市id',
  `allot_terminal` string COMMENT 'Pad端 非Pad端',
  `network_id` bigint COMMENT '网络制式',
  `network_desc` string COMMENT '网络制式描述',
  `deliver_type` int COMMENT '1.线下出库 2.天路散货',
  `deliver_type_desc` string COMMENT '散货方式 ',
  `recall_deliver_time` string COMMENT 'yyyy-MM-dd HH:mm:ss',
  `recall_in_storage_time` string COMMENT 'yyyy-MM-dd HH:mm:ss',
  `recall_recheck_finish_time` string COMMENT 'yyyy-MM-dd HH:mm:ss',
  `init_store_id` bigint COMMENT '初始进货门店id',
  `init_store_name` string COMMENT '初始进货门店名',
  `init_city_id` int COMMENT '初始门店城市ID',
  `init_city_name` string COMMENT '初始门店城市名',
  `allot_create_time` string COMMENT '调拨创建时间(最后一次调拨)',
  `allot_audit_time` string COMMENT '调拨审批时间(最后一次调拨)',
  `allot_storage_time` string COMMENT '调拨入库时间(最后一次调拨)',
  `purchase_order_source` int COMMENT '1：自主采购 2：自动采购 3：权益机采购',
  `purchaser_type` int COMMENT '采购方 1：总部 2：门店',
  `recall_type_new` int COMMENT '1：总部召回 2：门店召回 3:自动召回',
  `warrantyperiodvalue` string COMMENT '保修日期',
  `batteryhealthvalue` string COMMENT '电池容量',
  `colourname` string COMMENT '颜色',
  `warrantystatusvalue` string COMMENT '在保情况',
  `is_change_screen` string COMMENT '是否修换屏幕',
  `is_change_battery` string COMMENT '是否换电池',
  `staff_id` bigint COMMENT '店员uid',
  `staff_email` string COMMENT '店员email',
  `is_reserve_label` int COMMENT '是否预留标签1是 0 不是',
  `skyway_product_id` bigint COMMENT '天路商品id',
  `back_money` bigint COMMENT '退款金额，分',
  `back_time` string COMMENT '退款时间',
  `subdivision_grade` string COMMENT '细分等级',
  `surface_gold_level_name` string COMMENT '新成色等级',
  `ts_total_time` double COMMENT '同售上架累计时长，天',
  `book_total_time` double COMMENT '预定累计时长，天',
  `allot_total_time` double COMMENT '调拨累计时长，天',
  `first_ts_time` string COMMENT '首次同售上架时间',
  `store_province` string COMMENT '战区,进货门店id，如发生调拨，此处为调拨门店大区',
  `store_area` string COMMENT '大区,进货门店所属战区，如发生调拨，此处为调拨门店所属战区',
  `store_type_name` string COMMENT '门店类型中文名',
  `is_old_change` int COMMENT '是否以旧换优 1是 0否',
  `is_grille_broken` int COMMENT '音频网罩是否损坏,1是 0否',
  `is_refurbish` int COMMENT '是否整备,1是 0否',
  `is_refurbish_battery` int COMMENT '是否整备电池,1是 0否',
  `is_refurbish_screen` int COMMENT '是否打磨屏幕（整备）,1是 0否',
  `is_refurbish_scratch` int COMMENT '是否打磨划痕（整备）,1是 0否',
  `is_refurbish_grille` int COMMENT '是否整备音频网罩,1是 0否',
  `province` string COMMENT '如发生调拨，此处为调拨门店省份',
  `detail_address` string COMMENT '如发生调拨，此处为调拨门店详细地址',
  `store_biz_type` int COMMENT '如发生调拨，此处为调拨门店门店业务类型,1普通2直播',
  `battery_charging_times` int COMMENT '电池充电次数',
  `purchase_logistics_company` string COMMENT '采购物流公司',
  `purchase_logistics_collect_time` string COMMENT '采购物流揽件时间',
  `purchase_sign_collect_time` string COMMENT '采购物流签收时间',
  `purchase_from_warehouse_name` string COMMENT '采购物流发货仓',
  `purchase_oms_create_time` string COMMENT '采购发货单创建时间',
  `group_name` string COMMENT '门店所属小组名',
  `appearance_grade_id` int COMMENT '外观成色属性值ID',
  `appearance_grade_name` string COMMENT '外观成色属性值Name',
  `functional_grade_id` int COMMENT '功能成色属性值ID',
  `functional_grade_name` string COMMENT '功能成色属性值Name',
  `product_id` bigint COMMENT '转转商品id',
  `is_hour_mart` int COMMENT '是否上架小时达',
  `product_mart_info` string COMMENT '卖场信息',
  `union_id` string COMMENT '微信UnionID')
COMMENT '帮卖业务，线下门店零售业务宽表'
PARTITIONED BY (`dt` string);


-- ========================================================================
-- 表2：pro店线下零售订单表
-- hdp_ubu_zhuanzhuan_dw_c2b.dw_trade_sale_store_pro_retail_offline_data_full_1d
-- COMMENT '门店_Pro店零售订单数据；主键 order_id'
-- 分区 dt(yyyy-MM-dd)；关键字段：order_id / city_name / outbound_time / order_type /
--   store_name / deal_price(分) / deliver_type(0邮寄 4小时达)
-- ========================================================================
CREATE TABLE `hdp_ubu_zhuanzhuan_dw_c2b.dw_trade_sale_store_pro_retail_offline_data_full_1d`(
  `province` string COMMENT '省份',
  `region` string COMMENT '战区',
  `first_opening_time` string COMMENT '门店开业时间',
  `store_type` int COMMENT '门店类型',
  `store_type_name` string COMMENT '门店类型名称',
  `order_id` bigint COMMENT '订单id（对应中台父订单号）',
  `child_order_id` bigint COMMENT '子订单号',
  `order_type` int COMMENT '订单类型',
  `order_type_desc` string COMMENT '订单类型名',
  `state` int COMMENT '订单状态',
  `state_desc` string COMMENT '订单状态描述',
  `create_time` string COMMENT '订单创建时间',
  `info_id` bigint COMMENT '商品id',
  `qc_code` bigint COMMENT '质检码',
  `cate_id` bigint COMMENT '品类id',
  `cate_name` string COMMENT '品类名称',
  `buyer_id` bigint COMMENT '买家id',
  `seller_id` bigint COMMENT '卖家id',
  `city_id` bigint COMMENT '城市id',
  `city_name` string COMMENT '城市名称',
  `store_id` bigint COMMENT '门店id',
  `store_name` string COMMENT '门店名称',
  `staff_id` bigint COMMENT '销售人id',
  `staff_uid` bigint COMMENT '销售人uid',
  `staff_email` string COMMENT '销售人email',
  `staff_name` string COMMENT '销售人名称',
  `deal_price` bigint COMMENT '成交价,单位分',
  `pay_type` int COMMENT '支付方式',
  `pay_type_desc` string COMMENT '支付方式名称',
  `is_old_change` int COMMENT '是否已旧换新',
  `refund_time` string COMMENT '退货时间',
  `info_title` string COMMENT '商品描述',
  `points_money` bigint COMMENT '积分抵扣金额,单位分',
  `update_time` string COMMENT '更新时间',
  `finish_time` string COMMENT '订单完成时间',
  `info_num` int COMMENT '商品数量',
  `pack_amount` bigint COMMENT '红包金额',
  `pay_time` string COMMENT '支付时间',
  `market_channel` int COMMENT '销售渠道',
  `afs_create_time` string COMMENT '售后单创建时间',
  `afs_finish_time` string COMMENT '售后单完成时间',
  `afs_responsibility_type` string COMMENT '售后责任类型',
  `compensation_amount` bigint COMMENT '赔付金额,单位分',
  `is_afs` string COMMENT '是否售后',
  `storage_time` string COMMENT '入库时间',
  `outbound_time` string COMMENT '出库时间',
  `storage_age` int COMMENT '库龄',
  `capacity_desc` string COMMENT '容量',
  `colour_name` string COMMENT '颜色',
  `product_channel` string COMMENT '销售渠道',
  `appearance_condition_id` bigint COMMENT '外观成色id',
  `appearance_condition_name` string COMMENT '外观成色',
  `functional_condition_id` bigint COMMENT '功能成色id',
  `functional_condition_name` string COMMENT '功能成色',
  `condition_desc` string COMMENT '成色',
  `imei` string COMMENT 'imei',
  `sku_id` bigint COMMENT 'sku_id',
  `brand_id` bigint COMMENT '品牌id',
  `brand_name` string COMMENT '品牌名',
  `model_id` bigint COMMENT '机型id',
  `model_name` string COMMENT '机型名称',
  `purchase_channels` string COMMENT '进货渠道',
  `cost_price` bigint COMMENT '成本价，成本分',
  `skyway_product_id` bigint COMMENT '天路商品ID',
  `pack_id` bigint COMMENT '红包id',
  `total_amt` double COMMENT '红包金额',
  `union_id` string COMMENT '微信UnionID',
  `market_channel_name` string COMMENT '到店渠道',
  `market_sub_channel_name` string COMMENT '到店子渠道',
  `staff_group` string COMMENT '人员分组',
  `deliver_time` string COMMENT '订单发货时间（yyyy-MM-dd HH:mm:ss）',
  `deliver_type` int COMMENT '发货途径：0（邮寄）,4（小时达）',
  `goods_source` string COMMENT '商品来源',
  `pre_ref_time` string COMMENT '售前退款时间(yyyy-MM-dd HH:mm:ss)',
  `avg_info_price` double COMMENT '卖场成交均价')
COMMENT '门店_Pro店零售订单数据(该表记录门店Pro店非配件订单，含零售与售后过程；主键 order_id)'
PARTITIONED BY (`dt` string COMMENT 'yyyy-MM-dd');
