#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK_DIR="/Users/liangkun/Documents/产品工作"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

pass() {
  echo "PASS: $*"
}

require_file() {
  local file="$1"
  [[ -f "$file" ]] || fail "missing file: $file"
}

require_text() {
  local file="$1"
  local pattern="$2"
  if command -v rg >/dev/null 2>&1; then
    rg -q "$pattern" "$file" || fail "missing pattern in $file: $pattern"
  else
    grep -Eq "$pattern" "$file" || fail "missing pattern in $file: $pattern"
  fi
}

reject_text() {
  local file="$1"
  local pattern="$2"
  if command -v rg >/dev/null 2>&1; then
    ! rg -q "$pattern" "$file" || fail "forbidden pattern in $file: $pattern"
  else
    ! grep -Eq "$pattern" "$file" || fail "forbidden pattern in $file: $pattern"
  fi
}

SKILL_MD="$ROOT_DIR/SKILL.md"
BEHAVIOR_MD="$ROOT_DIR/references/behavior-model.md"
PATH_MODE_MD="$ROOT_DIR/references/path-constrained-mode.md"
ANDROID_MD="$ROOT_DIR/references/android-tool-layer.md"
OPENAI_YAML="$ROOT_DIR/agents/openai.yaml"
RESULT_PROMPT="$WORK_DIR/user-chance_test_result_export_prompt.md"
PROCESS_PROMPT="$WORK_DIR/user-chance_test_process_export_prompt.md"
AVD_RESULT_PROMPT="$WORK_DIR/user-chance_test_result_export_prompt_20260611_after_avd_fix.md"
TEST1_RESULT_INSTRUCTION="$WORK_DIR/user-chance_test1_goal_driven_result_export_instruction.md"
TEST2_RESULT_INSTRUCTION="$WORK_DIR/user-chance_test2_path_constrained_result_export_instruction.md"
TEST1_RESULT_INSTRUCTION_20260616="$WORK_DIR/user-chance_test1_result_export_instruction_20260616.md"
TEST2_RESULT_INSTRUCTION_20260616="$WORK_DIR/user-chance_test2_result_export_instruction_20260616.md"
RETEST1_RESULT_INSTRUCTION="$WORK_DIR/user-chance_retest1_result_export_instruction_20260615.md"
RETEST2_RESULT_INSTRUCTION="$WORK_DIR/user-chance_retest2_path_constrained_result_export_instruction_20260615.md"
RETEST3_RESULT_INSTRUCTION="$WORK_DIR/user-chance_retest3_generalization_result_export_instruction_20260615.md"
RETEST4_RESULT_INSTRUCTION="$WORK_DIR/user-chance_retest4_path_escape_result_export_instruction_20260615.md"
STANDALONE_PROCESS_PROMPT="$WORK_DIR/user-chance_process_export_instruction_20260611.md"
STANDALONE_PROCESS_PROMPT_20260612="$WORK_DIR/user-chance_process_export_instruction_20260612.md"
TIGHTENED_PROCESS_PROMPT_20260612="$WORK_DIR/user-chance_process_export_instruction_20260612_tightened.md"

require_file "$SKILL_MD"
require_file "$BEHAVIOR_MD"
require_file "$PATH_MODE_MD"
require_file "$ANDROID_MD"
require_file "$OPENAI_YAML"
require_file "$RESULT_PROMPT"
require_file "$PROCESS_PROMPT"
require_file "$AVD_RESULT_PROMPT"
require_file "$TEST1_RESULT_INSTRUCTION"
require_file "$TEST2_RESULT_INSTRUCTION"
require_file "$TEST1_RESULT_INSTRUCTION_20260616"
require_file "$TEST2_RESULT_INSTRUCTION_20260616"
require_file "$RETEST1_RESULT_INSTRUCTION"
require_file "$RETEST2_RESULT_INSTRUCTION"
require_file "$RETEST3_RESULT_INSTRUCTION"
require_file "$RETEST4_RESULT_INSTRUCTION"
require_file "$STANDALONE_PROCESS_PROMPT"
require_file "$STANDALONE_PROCESS_PROMPT_20260612"
require_file "$TIGHTENED_PROCESS_PROMPT_20260612"

skill_lines="$(wc -l < "$SKILL_MD" | tr -d ' ')"
[[ "$skill_lines" -le 500 ]] || fail "SKILL.md is too long: ${skill_lines} lines"

require_text "$SKILL_MD" "^name: user-chance$"
require_text "$SKILL_MD" "^description: .*转转.*体验问题.*机会点"
require_text "$SKILL_MD" "Agent 行动像用户，复盘像研究员"
require_text "$SKILL_MD" "references/android-tool-layer.md"
require_text "$SKILL_MD" "references/behavior-model.md"
require_text "$SKILL_MD" "references/path-constrained-mode.md"
require_text "$SKILL_MD" "Endpoint Resolution"
require_text "$SKILL_MD" "Mode Resolution"
require_text "$SKILL_MD" "User Simulation Kernel"
require_text "$SKILL_MD" "experiment_mode"
require_text "$SKILL_MD" "path_spec"
require_text "$SKILL_MD" "path_policy"
require_text "$SKILL_MD" "report_intent"
require_text "$SKILL_MD" "export_profile"
require_text "$SKILL_MD" "goal_parameter_map"
require_text "$SKILL_MD" "decision_concern_map"
require_text "$SKILL_MD" "evidence_seeking_behavior"
require_text "$SKILL_MD" "media_action"
require_text "$SKILL_MD" "route_hypothesis"
require_text "$SKILL_MD" "dynamic_user_state"
require_text "$SKILL_MD" "local_information_maturity"
require_text "$SKILL_MD" "target_entity_shift"
require_text "$SKILL_MD" "decision_status"
require_text "$SKILL_MD" "user_decision"
require_text "$SKILL_MD" "stop_reason"
require_text "$SKILL_MD" "stop_proof"
require_text "$SKILL_MD" "stop_basis"
require_text "$SKILL_MD" "observation_quality"
require_text "$SKILL_MD" "conclusion_level"
require_text "$SKILL_MD" "tool_constraint_impact"
require_text "$SKILL_MD" "legacy_goal_result"
require_text "$SKILL_MD" "tool_failure"
require_text "$SKILL_MD" "noticed_evidence"
require_text "$SKILL_MD" "global_evidence"
require_text "$SKILL_MD" "behavior_fidelity"
require_text "$SKILL_MD" "sample_validity"
require_text "$SKILL_MD" "path_compliance"
require_text "$SKILL_MD" "structured_summary"
require_text "$SKILL_MD" "summary.json"
require_text "$SKILL_MD" "Start State Validation"
require_text "$SKILL_MD" "start_state_validity"
require_text "$SKILL_MD" "entry_coverage"
require_text "$SKILL_MD" "stop_decision_split"
require_text "$SKILL_MD" "stop_trigger"
require_text "$SKILL_MD" "boundary_influence"
require_text "$SKILL_MD" "counterfactual_without_boundary"
require_text "$SKILL_MD" "evidence_strength"
require_text "$SKILL_MD" "自然语言优先"
require_text "$SKILL_MD" "少爷不需要手写"
require_text "$SKILL_MD" "内部归一化"
reject_text "$SKILL_MD" "goal_result: success"
reject_text "$SKILL_MD" "failed_reason"

require_text "$BEHAVIOR_MD" "user_action_view"
require_text "$BEHAVIOR_MD" "research_analysis_view"
require_text "$BEHAVIOR_MD" "User Simulation Kernel"
require_text "$BEHAVIOR_MD" "Experiment Configuration"
require_text "$BEHAVIOR_MD" "experiment_mode"
require_text "$BEHAVIOR_MD" "path_spec"
require_text "$BEHAVIOR_MD" "path_policy"
require_text "$BEHAVIOR_MD" "report_intent"
require_text "$BEHAVIOR_MD" "export_profile"
require_text "$BEHAVIOR_MD" "Persona Priors"
require_text "$BEHAVIOR_MD" "Goal Parameter Map"
require_text "$BEHAVIOR_MD" "Decision Concern Map"
require_text "$BEHAVIOR_MD" "Evidence Seeking Behavior"
require_text "$BEHAVIOR_MD" "Route Hypothesis"
require_text "$BEHAVIOR_MD" "Local Information Maturity"
require_text "$BEHAVIOR_MD" "Target Entity Shift"
require_text "$BEHAVIOR_MD" "Attention Filter"
require_text "$BEHAVIOR_MD" "Dynamic User State"
require_text "$BEHAVIOR_MD" "Decision Policy"
require_text "$BEHAVIOR_MD" "Friction Response"
require_text "$BEHAVIOR_MD" "Step Record Contract"
require_text "$BEHAVIOR_MD" "Outcome Contract"
require_text "$BEHAVIOR_MD" "Contract Invariants"
require_text "$BEHAVIOR_MD" "Anti-Script Rules"
require_text "$BEHAVIOR_MD" "decision_status"
require_text "$BEHAVIOR_MD" "user_decision"
require_text "$BEHAVIOR_MD" "stop_reason"
require_text "$BEHAVIOR_MD" "stop_proof"
require_text "$BEHAVIOR_MD" "stop_basis"
require_text "$BEHAVIOR_MD" "goal_parameter_map"
require_text "$BEHAVIOR_MD" "decision_concern_map"
require_text "$BEHAVIOR_MD" "evidence_seeking_behavior"
require_text "$BEHAVIOR_MD" "inspect_media"
require_text "$BEHAVIOR_MD" "media_action"
require_text "$BEHAVIOR_MD" "local_information_maturity"
require_text "$BEHAVIOR_MD" "allowed_next_action"
require_text "$BEHAVIOR_MD" "continue_browsing"
require_text "$BEHAVIOR_MD" "stop_defer"
require_text "$BEHAVIOR_MD" "stop_buy_ready"
require_text "$BEHAVIOR_MD" "stop_reject_ready"
require_text "$BEHAVIOR_MD" "禁止在任何主字段中输出"
require_text "$BEHAVIOR_MD" "最终候选"
require_text "$BEHAVIOR_MD" "marginal_value_low"
require_text "$BEHAVIOR_MD" "boundary_near"
require_text "$BEHAVIOR_MD" "target_entity_shift"
require_text "$BEHAVIOR_MD" "upgrade"
require_text "$BEHAVIOR_MD" "downgrade"
require_text "$BEHAVIOR_MD" "lateral"
require_text "$BEHAVIOR_MD" "tool_failure_record"
require_text "$BEHAVIOR_MD" "directional_signal"
require_text "$BEHAVIOR_MD" "behavior_assessment"
require_text "$BEHAVIOR_MD" "concern_realism"
require_text "$BEHAVIOR_MD" "evidence_behavior_authenticity"
require_text "$BEHAVIOR_MD" "样本有效性"
require_text "$BEHAVIOR_MD" "path_compliance"
require_text "$BEHAVIOR_MD" "structured_summary"
require_text "$BEHAVIOR_MD" "summary.json"
require_text "$BEHAVIOR_MD" "Start State Validity"
require_text "$BEHAVIOR_MD" "start_state_validity"
require_text "$BEHAVIOR_MD" "entry_coverage"
require_text "$BEHAVIOR_MD" "Stop Decision Split"
require_text "$BEHAVIOR_MD" "stop_decision_split"
require_text "$BEHAVIOR_MD" "stop_trigger"
require_text "$BEHAVIOR_MD" "boundary_influence"
require_text "$BEHAVIOR_MD" "counterfactual_without_boundary"
require_text "$BEHAVIOR_MD" "Evidence Strength"
require_text "$BEHAVIOR_MD" "evidence_strength"
require_text "$BEHAVIOR_MD" "strong_evidence"
require_text "$BEHAVIOR_MD" "single_run_signal"
require_text "$BEHAVIOR_MD" "agent_inference"
require_text "$BEHAVIOR_MD" "tool_limited"
require_text "$BEHAVIOR_MD" "自然语言解析"
require_text "$BEHAVIOR_MD" "内部归一化"
require_text "$BEHAVIOR_MD" "不要要求少爷手写"
reject_text "$BEHAVIOR_MD" "goal_result: success"
reject_text "$BEHAVIOR_MD" "failed_reason"
reject_text "$BEHAVIOR_MD" "至少看[[:space:]]*[0-9一二三四五六七八九十]"
reject_text "$BEHAVIOR_MD" "至少进入[[:space:]]*[0-9一二三四五六七八九十]"

require_text "$PATH_MODE_MD" "path_constrained"
require_text "$PATH_MODE_MD" "不是点击脚本"
require_text "$PATH_MODE_MD" "path_spec"
require_text "$PATH_MODE_MD" "path_policy"
require_text "$PATH_MODE_MD" "strict_replay"
require_text "$PATH_MODE_MD" "anchored_corridor"
require_text "$PATH_MODE_MD" "guided_with_escape"
require_text "$PATH_MODE_MD" "path_compliance"
require_text "$PATH_MODE_MD" "deviations"
require_text "$PATH_MODE_MD" "path_fit_assessment"
require_text "$PATH_MODE_MD" "goal_support"
require_text "$PATH_MODE_MD" "decision_support"
require_text "$PATH_MODE_MD" "self_correction_cost"
require_text "$PATH_MODE_MD" "path_goal_fit"
require_text "$PATH_MODE_MD" "自然语言输入"
require_text "$PATH_MODE_MD" "少爷不需要说"
require_text "$PATH_MODE_MD" "Agent 内部"

require_text "$ANDROID_MD" "resolve_android_endpoints.sh"
require_text "$ANDROID_MD" "start_android_avd.sh"
require_text "$ANDROID_MD" "自动启动"
require_text "$ANDROID_MD" "EMULATOR_HEADLESS"
require_text "$ANDROID_MD" "launchctl"
require_text "$ANDROID_MD" "idle-grpc-timeout"
require_text "$ANDROID_MD" "mobile-mcp"
require_text "$ANDROID_MD" "工具层失败不能直接写成产品体验问题"
require_text "$ROOT_DIR/scripts/start_android_avd.sh" "launchctl submit"
require_text "$ROOT_DIR/scripts/start_android_avd.sh" "idle-grpc-timeout 0"
require_text "$ROOT_DIR/scripts/start_android_avd.sh" "START_STABILITY_SECONDS"
require_text "$ROOT_DIR/scripts/mobile_mcp_healthcheck.mjs" "Device.*not found"
require_text "$ROOT_DIR/scripts/mobile_mcp_healthcheck.mjs" "Screenshot was not created"

require_text "$RESULT_PROMPT" "decision_status"
require_text "$RESULT_PROMPT" "user_decision"
require_text "$RESULT_PROMPT" "stop_reason"
require_text "$RESULT_PROMPT" "experiment_mode"
require_text "$RESULT_PROMPT" "path_policy"
require_text "$RESULT_PROMPT" "report_intent"
require_text "$RESULT_PROMPT" "export_profile"
require_text "$RESULT_PROMPT" "stop_proof"
require_text "$RESULT_PROMPT" "stop_basis"
require_text "$RESULT_PROMPT" "observation_quality"
require_text "$RESULT_PROMPT" "conclusion_level"
require_text "$RESULT_PROMPT" "tool_constraint_impact"
require_text "$RESULT_PROMPT" "legacy_goal_result"
require_text "$RESULT_PROMPT" "goal_parameter_map"
require_text "$RESULT_PROMPT" "decision_concern_map"
require_text "$RESULT_PROMPT" "evidence_seeking_behavior"
require_text "$RESULT_PROMPT" "inspect_media"
require_text "$RESULT_PROMPT" "media_action"
require_text "$RESULT_PROMPT" "local_information_maturity"
require_text "$RESULT_PROMPT" "allowed_next_action"
require_text "$RESULT_PROMPT" "continue_browsing"
require_text "$RESULT_PROMPT" "stop_defer"
require_text "$RESULT_PROMPT" "stop_buy_ready"
require_text "$RESULT_PROMPT" "stop_reject_ready"
require_text "$RESULT_PROMPT" "混合成熟度值"
require_text "$RESULT_PROMPT" "最终候选"
require_text "$RESULT_PROMPT" "target_entity_shift"
require_text "$RESULT_PROMPT" "upgrade"
require_text "$RESULT_PROMPT" "downgrade"
require_text "$RESULT_PROMPT" "lateral"
require_text "$RESULT_PROMPT" "behavior_assessment"
require_text "$RESULT_PROMPT" "behavior_fidelity"
require_text "$RESULT_PROMPT" "sample_validity"
require_text "$RESULT_PROMPT" "noticed_evidence"
require_text "$RESULT_PROMPT" "global_evidence"
require_text "$RESULT_PROMPT" "体验问题"
require_text "$RESULT_PROMPT" "产品机会点"
require_text "$RESULT_PROMPT" "path_compliance"
require_text "$RESULT_PROMPT" "structured_summary"
require_text "$RESULT_PROMPT" "summary.json"
require_text "$RESULT_PROMPT" "start_state_validity"
require_text "$RESULT_PROMPT" "entry_coverage"
require_text "$RESULT_PROMPT" "stop_decision_split"
require_text "$RESULT_PROMPT" "stop_trigger"
require_text "$RESULT_PROMPT" "boundary_influence"
require_text "$RESULT_PROMPT" "counterfactual_without_boundary"
require_text "$RESULT_PROMPT" "evidence_strength"
require_text "$RESULT_PROMPT" "strong_evidence"
require_text "$RESULT_PROMPT" "single_run_signal"
require_text "$RESULT_PROMPT" "agent_inference"
require_text "$RESULT_PROMPT" "tool_limited"
require_text "$RESULT_PROMPT" "path_goal_fit"
reject_text "$RESULT_PROMPT" "goal_result: success"
reject_text "$RESULT_PROMPT" "failed_reason"

require_text "$PROCESS_PROMPT" "Notice"
require_text "$PROCESS_PROMPT" "Interpret"
require_text "$PROCESS_PROMPT" "Update State"
require_text "$PROCESS_PROMPT" "Naturalness"
require_text "$PROCESS_PROMPT" "step_record"
require_text "$PROCESS_PROMPT" "experiment_mode"
require_text "$PROCESS_PROMPT" "path_policy"
require_text "$PROCESS_PROMPT" "report_intent"
require_text "$PROCESS_PROMPT" "export_profile"
require_text "$PROCESS_PROMPT" "goal_parameter_map"
require_text "$PROCESS_PROMPT" "decision_concern_map"
require_text "$PROCESS_PROMPT" "evidence_seeking_behavior"
require_text "$PROCESS_PROMPT" "inspect_media"
require_text "$PROCESS_PROMPT" "media_action"
require_text "$PROCESS_PROMPT" "route_hypothesis"
require_text "$PROCESS_PROMPT" "dynamic_user_state"
require_text "$PROCESS_PROMPT" "local_information_maturity"
require_text "$PROCESS_PROMPT" "allowed_next_action"
require_text "$PROCESS_PROMPT" "continue_browsing"
require_text "$PROCESS_PROMPT" "stop_defer"
require_text "$PROCESS_PROMPT" "stop_buy_ready"
require_text "$PROCESS_PROMPT" "stop_reject_ready"
require_text "$PROCESS_PROMPT" "混合成熟度值"
require_text "$PROCESS_PROMPT" "最终候选"
require_text "$PROCESS_PROMPT" "target_entity_shift"
require_text "$PROCESS_PROMPT" "decision_status"
require_text "$PROCESS_PROMPT" "user_decision"
require_text "$PROCESS_PROMPT" "stop_reason"
require_text "$PROCESS_PROMPT" "stop_proof"
require_text "$PROCESS_PROMPT" "stop_basis"
require_text "$PROCESS_PROMPT" "behavior_fidelity"
require_text "$PROCESS_PROMPT" "sample_validity"
require_text "$PROCESS_PROMPT" "path_compliance"
require_text "$PROCESS_PROMPT" "structured_summary"
require_text "$PROCESS_PROMPT" "summary.json"
require_text "$PROCESS_PROMPT" "start_state_validity"
require_text "$PROCESS_PROMPT" "entry_coverage"
require_text "$PROCESS_PROMPT" "stop_decision_split"
require_text "$PROCESS_PROMPT" "stop_trigger"
require_text "$PROCESS_PROMPT" "boundary_influence"
require_text "$PROCESS_PROMPT" "counterfactual_without_boundary"
require_text "$PROCESS_PROMPT" "evidence_strength"
require_text "$PROCESS_PROMPT" "strong_evidence"
require_text "$PROCESS_PROMPT" "single_run_signal"
require_text "$PROCESS_PROMPT" "agent_inference"
require_text "$PROCESS_PROMPT" "tool_limited"
require_text "$PROCESS_PROMPT" "path_goal_fit"
reject_text "$PROCESS_PROMPT" "goal_result: success"
reject_text "$PROCESS_PROMPT" "failed_reason"

require_text "$TEST1_RESULT_INSTRUCTION" "start_state_validity"
require_text "$TEST1_RESULT_INSTRUCTION" "entry_coverage"
require_text "$TEST1_RESULT_INSTRUCTION" "stop_decision_split"
require_text "$TEST1_RESULT_INSTRUCTION" "stop_trigger"
require_text "$TEST1_RESULT_INSTRUCTION" "boundary_influence"
require_text "$TEST1_RESULT_INSTRUCTION" "evidence_strength"
require_text "$TEST1_RESULT_INSTRUCTION" "path_compliance"
require_text "$TEST1_RESULT_INSTRUCTION" "not_applicable"
reject_text "$TEST1_RESULT_INSTRUCTION" "goal_result: success"
reject_text "$TEST1_RESULT_INSTRUCTION" "failed_reason"

require_text "$TEST2_RESULT_INSTRUCTION" "path_compliance"
require_text "$TEST2_RESULT_INSTRUCTION" "goal_support"
require_text "$TEST2_RESULT_INSTRUCTION" "decision_support"
require_text "$TEST2_RESULT_INSTRUCTION" "self_correction_cost"
require_text "$TEST2_RESULT_INSTRUCTION" "path_goal_fit"
require_text "$TEST2_RESULT_INSTRUCTION" "start_state_validity"
require_text "$TEST2_RESULT_INSTRUCTION" "entry_coverage"
require_text "$TEST2_RESULT_INSTRUCTION" "stop_trigger"
require_text "$TEST2_RESULT_INSTRUCTION" "boundary_influence"
require_text "$TEST2_RESULT_INSTRUCTION" "evidence_strength"
reject_text "$TEST2_RESULT_INSTRUCTION" "goal_result: success"
reject_text "$TEST2_RESULT_INSTRUCTION" "failed_reason"

require_text "$STANDALONE_PROCESS_PROMPT" "experiment_mode"
require_text "$STANDALONE_PROCESS_PROMPT" "path_policy"
require_text "$STANDALONE_PROCESS_PROMPT" "report_intent"
require_text "$STANDALONE_PROCESS_PROMPT" "export_profile"
require_text "$STANDALONE_PROCESS_PROMPT" "goal_parameter_map"
require_text "$STANDALONE_PROCESS_PROMPT" "decision_concern_map"
require_text "$STANDALONE_PROCESS_PROMPT" "evidence_seeking_behavior"
require_text "$STANDALONE_PROCESS_PROMPT" "inspect_media"
require_text "$STANDALONE_PROCESS_PROMPT" "media_action"
require_text "$STANDALONE_PROCESS_PROMPT" "local_information_maturity"
require_text "$STANDALONE_PROCESS_PROMPT" "allowed_next_action"
require_text "$STANDALONE_PROCESS_PROMPT" "混合成熟度值"
require_text "$STANDALONE_PROCESS_PROMPT" "最终候选"
require_text "$STANDALONE_PROCESS_PROMPT" "target_entity_shift"
require_text "$STANDALONE_PROCESS_PROMPT" "stop_basis"
require_text "$STANDALONE_PROCESS_PROMPT" "upgrade"
require_text "$STANDALONE_PROCESS_PROMPT" "downgrade"
require_text "$STANDALONE_PROCESS_PROMPT" "lateral"
require_text "$STANDALONE_PROCESS_PROMPT" "path_compliance"
require_text "$STANDALONE_PROCESS_PROMPT" "structured_summary"
require_text "$STANDALONE_PROCESS_PROMPT" "summary.json"
require_text "$STANDALONE_PROCESS_PROMPT" "start_state_validity"
require_text "$STANDALONE_PROCESS_PROMPT" "entry_coverage"
require_text "$STANDALONE_PROCESS_PROMPT" "stop_trigger"
require_text "$STANDALONE_PROCESS_PROMPT" "boundary_influence"
require_text "$STANDALONE_PROCESS_PROMPT" "evidence_strength"
reject_text "$STANDALONE_PROCESS_PROMPT" "goal_result: success"
reject_text "$STANDALONE_PROCESS_PROMPT" "failed_reason"

require_text "$STANDALONE_PROCESS_PROMPT_20260612" "experiment_mode"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "path_policy"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "report_intent"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "export_profile"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "goal_parameter_map"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "decision_concern_map"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "evidence_seeking_behavior"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "inspect_media"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "media_action"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "local_information_maturity"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "allowed_next_action"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "continue_browsing"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "stop_defer"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "stop_buy_ready"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "stop_reject_ready"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "混合成熟度值"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "最终候选"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "target_entity_shift"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "stop_basis"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "path_compliance"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "structured_summary"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "summary.json"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "start_state_validity"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "entry_coverage"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "stop_trigger"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "boundary_influence"
require_text "$STANDALONE_PROCESS_PROMPT_20260612" "evidence_strength"
reject_text "$STANDALONE_PROCESS_PROMPT_20260612" "goal_result: success"
reject_text "$STANDALONE_PROCESS_PROMPT_20260612" "failed_reason"

require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "experiment_mode"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "path_policy"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "report_intent"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "export_profile"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "goal_parameter_map"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "decision_concern_map"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "evidence_seeking_behavior"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "inspect_media"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "media_action"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "local_information_maturity"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "allowed_next_action"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "continue_browsing"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "stop_defer"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "stop_buy_ready"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "stop_reject_ready"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "混合成熟度值"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "最终候选"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "target_entity_shift"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "stop_basis"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "path_compliance"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "structured_summary"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "summary.json"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "start_state_validity"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "entry_coverage"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "stop_trigger"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "boundary_influence"
require_text "$TIGHTENED_PROCESS_PROMPT_20260612" "evidence_strength"
reject_text "$TIGHTENED_PROCESS_PROMPT_20260612" "goal_result: success"
reject_text "$TIGHTENED_PROCESS_PROMPT_20260612" "failed_reason"

require_text "$AVD_RESULT_PROMPT" "decision_status"
require_text "$AVD_RESULT_PROMPT" "user_decision"
require_text "$AVD_RESULT_PROMPT" "stop_reason"
require_text "$AVD_RESULT_PROMPT" "stop_proof"
require_text "$AVD_RESULT_PROMPT" "stop_basis"
require_text "$AVD_RESULT_PROMPT" "experiment_mode"
require_text "$AVD_RESULT_PROMPT" "path_policy"
require_text "$AVD_RESULT_PROMPT" "report_intent"
require_text "$AVD_RESULT_PROMPT" "export_profile"
require_text "$AVD_RESULT_PROMPT" "decision_concern_map"
require_text "$AVD_RESULT_PROMPT" "evidence_seeking_behavior"
require_text "$AVD_RESULT_PROMPT" "path_compliance"
require_text "$AVD_RESULT_PROMPT" "structured_summary"
require_text "$AVD_RESULT_PROMPT" "summary.json"
require_text "$AVD_RESULT_PROMPT" "start_state_validity"
require_text "$AVD_RESULT_PROMPT" "entry_coverage"
require_text "$AVD_RESULT_PROMPT" "stop_decision_split"
require_text "$AVD_RESULT_PROMPT" "stop_trigger"
require_text "$AVD_RESULT_PROMPT" "boundary_influence"
require_text "$AVD_RESULT_PROMPT" "counterfactual_without_boundary"
require_text "$AVD_RESULT_PROMPT" "evidence_strength"
require_text "$AVD_RESULT_PROMPT" "launchctl"
require_text "$AVD_RESULT_PROMPT" "idle-grpc-timeout"
reject_text "$AVD_RESULT_PROMPT" "goal_result: success"
reject_text "$AVD_RESULT_PROMPT" "failed_reason"

for file in "$SKILL_MD" "$BEHAVIOR_MD"; do
  require_text "$file" "mode_lock"
  require_text "$file" "tool_friction"
  require_text "$file" "decision_closure"
  require_text "$file" "mode_validity"
  require_text "$file" "tool_friction_impact"
  require_text "$file" "medium-high"
  require_text "$file" "low-medium"
done

for file in "$BEHAVIOR_MD" "$PATH_MODE_MD"; do
  require_text "$file" "followed_with_correction"
  require_text "$file" "deviated_with_correction"
  require_text "$file" "escaped"
  require_text "$file" "invalid"
done

require_text "$BEHAVIOR_MD" "Tool Friction Isolation"
require_text "$BEHAVIOR_MD" "Decision Closure"
require_text "$BEHAVIOR_MD" "flow_evidence"
require_text "$BEHAVIOR_MD" "decision_evidence"
require_text "$BEHAVIOR_MD" "product_pattern"
require_text "$PATH_MODE_MD" "入口被尝试"

for file in \
  "$RESULT_PROMPT" \
  "$PROCESS_PROMPT" \
  "$AVD_RESULT_PROMPT" \
  "$TEST1_RESULT_INSTRUCTION" \
  "$TEST2_RESULT_INSTRUCTION" \
  "$TEST1_RESULT_INSTRUCTION_20260616" \
  "$TEST2_RESULT_INSTRUCTION_20260616" \
  "$RETEST1_RESULT_INSTRUCTION" \
  "$RETEST2_RESULT_INSTRUCTION" \
  "$RETEST3_RESULT_INSTRUCTION" \
  "$RETEST4_RESULT_INSTRUCTION" \
  "$STANDALONE_PROCESS_PROMPT" \
  "$STANDALONE_PROCESS_PROMPT_20260612" \
  "$TIGHTENED_PROCESS_PROMPT_20260612"; do
  require_text "$file" "mode_validity"
  require_text "$file" "tool_friction"
  require_text "$file" "tool_friction_impact"
  require_text "$file" "decision_closure"
done

for file in \
  "$RESULT_PROMPT" \
  "$PROCESS_PROMPT" \
  "$AVD_RESULT_PROMPT" \
  "$TEST1_RESULT_INSTRUCTION" \
  "$TEST2_RESULT_INSTRUCTION" \
  "$TEST1_RESULT_INSTRUCTION_20260616" \
  "$TEST2_RESULT_INSTRUCTION_20260616" \
  "$RETEST1_RESULT_INSTRUCTION" \
  "$RETEST2_RESULT_INSTRUCTION" \
  "$RETEST3_RESULT_INSTRUCTION" \
  "$RETEST4_RESULT_INSTRUCTION" \
  "$STANDALONE_PROCESS_PROMPT" \
  "$STANDALONE_PROCESS_PROMPT_20260612" \
  "$TIGHTENED_PROCESS_PROMPT_20260612"; do
  require_text "$file" "local_information_maturity"
  require_text "$file" "maturity"
  require_text "$file" "low.*medium.*high|low.*high.*medium|medium.*low.*high"
  require_text "$file" "medium-high"
  require_text "$file" "low-medium"
done

for file in \
  "$RESULT_PROMPT" \
  "$PROCESS_PROMPT" \
  "$AVD_RESULT_PROMPT" \
  "$TEST2_RESULT_INSTRUCTION" \
  "$RETEST2_RESULT_INSTRUCTION" \
  "$RETEST4_RESULT_INSTRUCTION" \
  "$STANDALONE_PROCESS_PROMPT" \
  "$STANDALONE_PROCESS_PROMPT_20260612" \
  "$TIGHTENED_PROCESS_PROMPT_20260612"; do
  require_text "$file" "followed_with_correction"
  require_text "$file" "deviated_with_correction"
  require_text "$file" "escaped"
  require_text "$file" "invalid"
  require_text "$file" "self_correction_cost=high"
done

for file in \
  "$RESULT_PROMPT" \
  "$PROCESS_PROMPT" \
  "$AVD_RESULT_PROMPT" \
  "$STANDALONE_PROCESS_PROMPT" \
  "$STANDALONE_PROCESS_PROMPT_20260612" \
  "$TIGHTENED_PROCESS_PROMPT_20260612"; do
  require_text "$file" "flow_evidence"
  require_text "$file" "decision_evidence"
  require_text "$file" "product_pattern"
done

bash -n "$ROOT_DIR/scripts/resolve_android_endpoints.sh"
bash -n "$ROOT_DIR/scripts/start_android_avd.sh"
bash -n "$ROOT_DIR/scripts/check_zhuanzhuan_android_env.sh"
node --check "$ROOT_DIR/scripts/mobile_mcp_healthcheck.mjs" >/dev/null

pass "user-chance skill contract"
